upstream amneher_wsgi {
    # This should match the socket defined in uwsgi.
    server 127.0.0.1:8010;
}

server {
    listen 80;
    server_name amneher;
    server_name ngnr.us;
    server_name amneher.com;
    #return 301 https://amneher.com$request_uri;
}