[uwsgi]
# http://uwsgi-docs.readthedocs.org/en/latest/Configuration.html
# Placeholders
localroot = /home/amneher/amnehercom

plugins=python3
chdir=%(localroot)
home=%(localroot)/.ve
env=DJANGO_SETTINGS_MODULE=src.amneher.settings
env=LANG='en_US.UTF-8' DJANGO_SETTINGS_MODULE=src.amneher.settings
module=src.amneher.wsgi:application

# File socket have less overhead, but can have permission issues.
#socket=%(localroot)/%n.sock

# Use a port, more overhead, but no permissions issues.
socket=:8010

# Running an http-socket serves HTTP natively.
#http-socket=localhost:8010

# Run a couple instances.
processes=2

# http://uwsgi-docs.readthedocs.org/en/latest/MasterFIFO.html
master-fifo=%(localroot)/var/%n.fifo
vaccuum=True
max-requests=1
daemonize=%(localroot)/var/log/%n.log
touch-workers=%(localroot)/sundry/uwsgi.ini
touch-workers-reload=%(localroot)/src/amneher/wsgi.py

py-autoreload=5

